# Generated by Django 5.1.7 on 2025-03-30 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="song",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="song",
            name="description",
        ),
        migrations.RemoveField(
            model_name="song",
            name="genre",
        ),
        migrations.AddField(
            model_name="song",
            name="duration",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="song",
            name="file",
            field=models.FileField(upload_to="music/"),
        ),
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="music.album",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="music.artist",
            ),
        ),
        migrations.CreateModel(
            name="UserPlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("songs", models.ManyToManyField(to="music.song")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
