# Generated by Django 5.1.7 on 2025-03-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_album_artist_remove_song_artist_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
