# Generated by Django 5.1.7 on 2025-04-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_blogpost_comment_post_privatenote"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
